### PR TITLE
Used 'Horizontal' and 'Vertical' Margin and Paddings 

### PR DESCRIPTION
**Pull request by isiko**
# Description
- In some places, `paddingLeft` and `paddingRight` can be combined into `paddingHorizontal`
  - Same can be done with margins, and there is also a similar approach for combining
  - This is the same for `*Start` and `*End` Attributes
- `*Top` and `*Bottom` Attributes can also sometimes be converted to one `*Vertical` Attribute

> I already made a similar Pull-Request, but somehow my branch got messed up 😕 (see #446 )

### CODE REVIEW

**Comment by johnjohndoe** [comment]
> I already made a similar Pull-Request, but somehow my branch got messed up :confused: 

That happens. :shrug: Next time you got stuck please contact me before you open a new pull request so we can sort it out together.

**Comment by johnjohndoe** [comment]
Side note about commit messages:

> Used 'Horizontal' and 'Vertical' Margin and Paddings

Please have a look at the _"Active Voice"_ section in [this article](https://reflectoring.io/meaningful-commit-messages/) and consider using **present tense** in your commit messages for consistency in this repository.

**Comment by isiko** [comment]
> Please have a look at the _"Active Voice"_ section in [this article](https://reflectoring.io/meaningful-commit-messages/) and consider using **present tense** in your commit messages for consistency in this repository.

Updated the commit👍

**Review by johnjohndoe — APPROVED** [review]
Thank you for updating the files. :nail_care: 

I learned that the attributes are available [since API 26](https://developer.android.com/reference/android/R.attr#paddingHorizontal). :bulb: 

# Minor corrections
- I applied **automatic** formatting by Android Studio. Please add [this macro](https://stackoverflow.com/questions/946993/intellij-reformat-on-file-save/5581992#5581992).
- I removed **pure** formatting changes which are not related to the changes. These should be committed **separately**.
- I removed `android:scrollbarStyle="outsideOverlay"` which seems to be reappeared due to the last **rebase**.

**Pull request merged**
