### PR TITLE
Adjust clock icon position

### LINKED ISSUE #318: Adjust clock/time icon positioning and spacing
# Description
- The clock icon which is used in the session details screen looks somewhat odd positioned.

  Session details clock icon

# TODOs
- [x] Adjust either the SVG icon itself or the positioning or spacing.
- [x] Check different layout files for smartphones and tablets
- [x] Check the spacing with different leading numbers in the text string (hardcoding text temporary is fine)
- [x] Provide screenshots of before and after in your pull request

# Hints
- Resources to start of with
  - assets/access-time.svg
  - drawable/ic_access_time.xml
  - app/src/main/res/layout/session_detailbar.xml
  - app/src/main/res/layout/session_detailbar_large.xml
  - tbc.

### PR DESCRIPTION
**Pull request by minibugdev**
# Description
- The clock icon in the session details screen looks somewhat odd positioned.
- Device Pixel4 - API 28 and Nexus10 - API 29 emulators.

# Before
Before on mobile
Before on tablet

# After
- Add missing `android:drawablePadding` to clock icon to fixed it.

After on mobile
After on tablet

Resolves #318

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@minibugdev Thanks for working on this issue. Can you please add a "I am working on this" comment in the corresponding #318 issue so I can assign you to it? 

With regards to the icons I feel they also could be moved down a bit to better align with the text. Have you tried this? Is this possible without cutting the icon off?

Something seems to be wrong with the Travis CI build in this pull request. I not sure sure if you can do something about it. Please let me know if you have an idea why the automatic builds have not started.

**Comment by minibugdev** [comment]
Thanks @johnjohndoe

Already comment and let me try to adjust an icon.

After, I checked the CI cofig it excluded only tag version. So, I still have no idea why it's not running.

**Comment by johnjohndoe** [comment]
@minibugdev Okay. Don't worry about the CI. I will try to find out what's going wrong there.

**Comment by minibugdev** [comment]
Hi @johnjohndoe,

I'm looking for ways to adjust them by coding but I couldn't find any solution. So, I figure out the issue by adjust vector position on abode XD and import to new one to replace them.

The results as below.

### On mobile
Mobile

### On tablet
Tablet

**Comment by johnjohndoe** [comment]
This looks much better. :+1: I was not aware that the padding was missing in the layout files.
Modifying the original icons is perfectly fine. Thanks for also updating the SVGs, too.

With regards to your commit messages: can you please revise them: I like you to answer the question [_"Why did you change the icon?"_](https://github.com/EventFahrplan/EventFahrplan/blob/master/CONTRIBUTING.md). This will make it easier to somebody seeing the commit to understand your intention. This is especially helpful when graphical assets are modified where it is hard to grasp the actual change from.
If you need help here please let me know. Hint `git rebase --interactive` is your friend.
Feel free to force push your `feature/session-detail-icon-position` branch to update this pull request.

Up for another pull request if you like: the _location icon_ looks like it uses a different stroke width than the _clock icon_ and therefore it appears a bit thinker.

With regards to [Hacktoberfest](https://hacktoberfest.digitalocean.com/), do you want me to wait till October 1st to merge the pull request?

**Comment by minibugdev** [comment]
Hi @johnjohndoe,

I already update commit message and location icon stroke.

For `Hacktoberfest`, I think it won't count because this PR was before 1st October. So, don't worry about them :)

The results as below.

### On mobile
Mobile

### On tablet
Tablet

**Comment by johnjohndoe** [comment]
My pixel eye still spots a little offset ... I drew a half-transparent box over the area ... it shows that the room icon is 2 pixels above but I would say it still appears centered horizontally. The clock icon however sits a bit to far down. Can you center it, too?

Please also mention that and why you adjusted the stroke of the room icon in the respective commit message.

**Comment by johnjohndoe** [comment]
@minibugdev Please let me know if I can help with the pull request - but take your time if you are busy these days.

**Comment by minibugdev** [comment]
@johnjohndoe I'm on vacation, maybe next week I'll update the PR. Sorry for not getting back to you sooner.

**Comment by johnjohndoe** [comment]
@minibugdev All good. No reason for an excuse. Enjoy your vacation! :beach_umbrella:

**Comment by johnjohndoe** [comment]
@minibugdev I hope you have recharged your :battery: Once you have time I have this waiting for you.

**Comment by minibugdev** [comment]
Hi @johnjohndoe, I'm so sorry to reply late.
I just finished the PR the result as below.

Screen Shot

**Review by johnjohndoe — APPROVED** [review]
@minibugdev That looks great! Thank you for the adjustments.

I successfully tested it on a Pixel 2, Android 10 and a Nexus 9, Android 7.1.1. :+1: Besides that, I let Android Studio format `ic_access_time.xml` and I rebased your branch onto the latest commit on `master`. From my side your branch is ready to merge :smiley:

**Pull request merged**
