### PR TITLE
Enable multi-window support

### PR DESCRIPTION
**Pull request by bashtian**
https://developer.android.com/guide/topics/ui/multi-window#configuring

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@bashtian, sorry that I did not have time to test this during 35C3 anymore.
Can you please provide screenshots of the app without and with your changes? Feel free to take photos with a second device if this is easier.

**Comment by bashtian** [comment]
Sorry for the delay. 

This change is needed for Samsung Dex mode. I tested it on my Samsung Tab S4 and with this change I can resize the window.

It's explained in the Samsung docs under "Enabling Multi-Window support" https://developer.samsung.com/samsung-dex/modify-optimizing

**Comment by johnjohndoe** [comment]
@bashtian Thank you for the clarification. I think I can integrate this. Please do me the following favors:

- Add screenshots to this pull request to visually document the behavior change for anyone who does not have access to such a device.
- Add the Samsung link to your commit message.
- State in the commit message that this change is intended for Samsung devices.
- Rebase your branch onto the latest commit on `master`.

Please `git amend` your changes to the existing commit and update your branch and this pull request via `git push --force origin patch-1`. If you need any help with this please let me know.

**Comment by bashtian** [comment]
I updated the pull request. A screenshot does not really show the changes.

Before (not possible to resize) :
device-2019-01-20-111109

After (resizable):
device-2019-01-20-110943

**Comment by johnjohndoe** [comment]
@bashtian Thank you for the update. One thing I just noticed is that you did not apply the XML attribute to all activities. Is this on purpose or did you forget the remaining entries in the _AndroidManifest.xml_.

**Comment by bashtian** [comment]
True, I missed these Activities. I have updated the commit rebased with the master branch.

**Pull request merged**
