### PR TITLE
Updated de (German) translation

### PR DESCRIPTION
**Pull request by squeezer11**
Commit made via [Stringlate](https://github.com/LonamiWebs/Stringlate)

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@squeezer11 Please explain the **intention** of your change. Please **avoid reformatting** the files since it makes it cumbersome to spot the actual change you made.
Further, you broke the XML file as you can see from the test build on Travis CI.
Feel free to force push **your** branch once you cleaned up your commit.

**Comment by squeezer11** [comment]
hi, i had the intention to correct the translations, because there are some translations made before that makes completely another sense which do not match the original text on english. thats why i had corrected the german translation strings. by the way, i am german to fully understand it.

best regards

squeezer11

**Comment by squeezer11** [comment]
sorry for the reformatting. my mistake

**Comment by johnjohndoe** [comment]
@squeezer11 Thank you for the update. I will take a look as soon as the build error is fixed. Let me know if you need help with that.

**Comment by johnjohndoe** [comment]
@squeezer11 Are you going to update your pull request?

**Comment by johnjohndoe** [comment]
I cleaned up your pull request and picked a few of you suggestions into a [new pull request](https://github.com/EventFahrplan/EventFahrplan/pull/78).

**Comment by johnjohndoe** [comment]
Merged here: https://github.com/EventFahrplan/EventFahrplan/commit/bde32f5df26ccc0e29ccfbf7cc2e32242ff93897

**Pull request closed without merging**
