### PR TITLE
Add applications using this library

### PR DESCRIPTION
**Pull request by akarsh**
# Description
- Other libraries contain a section on applications using those libraries. Which makes it easy for the people who want to use this library having a quick glance on those applications.
e.g. 
1. library name - [osmdroid](https://github.com/osmdroid/osmdroid) 
   link: [Applications Using osmdroid](https://github.com/osmdroid/osmdroid/wiki/Applications-Using-osmdroid)
2. library name - [Universal Image Loader](https://github.com/nostra13/Android-Universal-Image-Loader) 
  link: [Applications using Universal Image Loader](https://github.com/nostra13/Android-Universal-Image-Loader#applications-using-universal-image-loader)

# Before
- The readme section does not contain any info on other applications using eventfahrplan.
Screen Shot 2019-10-03 at 18 26 53

# After
- The readme section now contains a sentence that links to a markdown file - applications using eventfahrplan
Screen Shot 2019-10-03 at 18 27 59

Screenshot_2019-10-03 akarsh EventFahrplan

### CODE REVIEW

**Comment by akarsh** [comment]
@hartwork  Thanks for the review.
I deleted earlier the fork repo on my GitHub as there was a different PR merged and did not thought this PR branch which points to the fork repo is also now deleted and shown as `unkown repository`. But I have a local copy and was able to restore the fork repo and the branch - https://github.com/akarsh/EventFahrplan/tree/add_applications_using_this_library

Since I don't have the access rights to update the branch with the PR.
@johnjohndoe / @hartwork  can you update the PR branch and point it to this branch - https://github.com/akarsh/EventFahrplan/tree/add_applications_using_this_library ?

I find this answer - https://webapps.stackexchange.com/questions/124056/can-you-add-to-a-github-pull-request-after-the-source-repo-is-deleted useful. May be you can give it a try or should I open a new PR and do the mentioned changes?

 
-------------

> Spaces in filenames doe not seem like a good idea to me. Does anything prevent use of underscores or dashes in filenames instead of spaces?

There is no reason. I prefer using spaces in naming files :D so I just used it. I will change them to underscores.

------------
>Added image files have not been optimized using a lossless compressor, yet. e.g. zopflipng gets FOSSGIS 2019 Programm.png down to 75% original size with no sacrifice in quality.

I did not use any image compression algorithms. In the example you used this repo - https://github.com/google/zopfli ? to perform the compression.


-------------
>The 35c3 entry could use an update for 36c3 now
I agree I will change it

**Comment by johnjohndoe** [comment]
> @johnjohndoe / @hartwork can you update the PR branch and point it to this branch - https://github.com/akarsh/EventFahrplan/tree/add_applications_using_this_library ?
> 
> I find this answer - https://webapps.stackexchange.com/questions/124056/can-you-add-to-a-github-pull-request-after-the-source-repo-is-deleted useful. May be you can give it a try ...

Hi @akarsh. I was also surprised that you deleted your whole fork. Nevertheless, please feel free to try to reconnect your branch with this pull request. I am interested as well if this is possible. I believe a good starting point is that you forked this repository once again - so this connection is given. Now I suggest that you try to force push your branch (it must have the same name as the original branch) and see if GitHub automatically picks it up as the former branch of this pull request. To me it would make sense since the original Git commit is around (if you did not change it locally) and the branch names match, as stated before. But we do not know what mechanisms GitHub implemented.

Another option I see is to contact the GitHub support. They should certainly be able to reconnect your branch and this pull request.

If anything goes wrong - do not worry - I have a local copy of the branch, too.

---

With regards to the pull request itself: I will review and leave a general statement as soon as I have time to do so.

**Comment by hartwork** [comment]
> @johnjohndoe / @hartwork can you update the PR branch and point it to this branch - https://github.com/akarsh/EventFahrplan/tree/add_applications_using_this_library ?

I don't have any permissions here so I cannot help on that front.

> There is no reason. I prefer using spaces in naming files :D so I just used it. I will change them to underscores.

Thank you! :+1: 

> > Added image files have not been optimized using a lossless compressor, yet. e.g. zopflipng gets FOSSGIS 2019 Programm.png down to 75% original size with no sacrifice in quality.
> 
> I did not use any image compression algorithms. In the example you used this repo - https://github.com/google/zopfli ? to perform the compression.

Yes, that's the one. Some distros have recent packaging for it, some don't. I used optipng -o7 before that but zopflipng produces even smaller files in my experience.

> > The 35c3 entry could use an update for 36c3 now
> 
> I agree I will change it

Thank you! :+1:

**Comment by johnjohndoe** [comment]
@akarsh Finally, I like to reply to your pull request. It took me a bit longer.

You are referring to this project as a "library". To clarify, this project is technically not a "library" but a multi-modules "Android application" project. It is however set up in a way which allows to customize it feature-wise and visually with a minimum of effort for an event. You could say it is a "white label" or "blue print". The Android plugin for Gradle facilitates this kind of setup by providing "product flavors".

> Other libraries contain a section on applications using those libraries.

That's true. I do this myself for a few libraries which I maintain.

> Which makes it easy for the people who want to use this library having a quick glance on those applications.

In contrast to libraries I do not yet see a benefit of providing a list of applications which have been built based on this project. The applications have a limited life time and their app icons change at least once a year. I therefore see the cost of maintaining this list.
Can you please explain what exactly you are aiming to ease? Maybe there is an alternative way to satisfy the need you identified.

**Comment by akarsh** [comment]
I did not know that this project was not a library earlier. So I compared with libraries.

> Can you please explain what exactly you are aiming to ease? Maybe there is an alternative way to satisfy the need you identified.

It would be more convenient to see whoever is checking this project on GitHub to see how this project is used in applications. This was the only aim. I don't know if there is another way to fulfil this convenience of a quick glance. Feel free to close this PR. As I did not estimate the overhead cost of maintaining this list.

**Comment by johnjohndoe** [comment]
> It would be more convenient to see whoever is checking this project on GitHub to see if this project is used in applications.

Would this be satisfied in your perspective when we add links to the event names in the README?

Before:
> EventFahrplan is a viewer for event schedules for instance Chaos Computer Club e.V. events such as Chaos Communication Camp or Chaos Communication Congress.

After:
> EventFahrplan is a viewer for event schedules for instance Chaos Computer Club e.V. events such as [Chaos Communication Camp](https://play.google.com/store/apps/details?id=info.metadude.android.cccamp.schedule) or [Chaos Communication Congress](https://play.google.com/store/apps/details?id=info.metadude.android.congress.schedule).

**Comment by akarsh** [comment]
It looks good. The links make it easy to find the event example apps.
This would suffice

**Comment by johnjohndoe** [comment]
:heavy_check_mark: Done in b3a9546f50447fab5b1c51238986c662aeb6457c.

**Comment by akarsh** [comment]
Nice 👍

**Pull request closed without merging**
