### PR TITLE
Random housekeeping

### PR DESCRIPTION
**Pull request by johnjohndoe**
# Description
- This branch contains a few unrelated cleanups. Please refer to the individual commit messages for the details.

# Successfully tested on
with `ccc36c3` flavor, `release` build
- :heavy_check_mark: Pixel 2 device, Android 10 (API 29)

### CODE REVIEW

**Review by cketti — APPROVED** [review]
Typo in the commit message "Fail fast of bundle extra is missing." 
Otherwise, LGTM

**Comment by johnjohndoe** [comment]
Thanks. Typo is fixed.

I would have expected that classes in other modules are also pointed out by the _explicit API_ mode. Do you understand why only the `engelsystem` module is affected?

**Comment by johnjohndoe** [comment]
@cketti Looks like there is [still issues](https://youtrack.jetbrains.com/issue/KT-37652) with _explicit API_ mode and Android. Do you also think I should leave it out for now?

**Comment by cketti** [comment]
I don't see the value of committing to a public API inside your own app. It's not like you're publishing parts of it as an independent library that can be used by others.

**Comment by johnjohndoe** [comment]
I think it is a nice addition to `internal` to clearly define the public API of a library module, too. - Still, I am patient enough to wait for its "completion". I will remove the commit here.

**Pull request merged**
